### ISSUE TITLE
[Bug] - Account already exists no alerts

### ISSUE THREAD

**Issue by songz** [garageScript/databases#127]
As a user, when I try to create an account and account already exists, there is no feedback. It feels like nothing happened. 

![Screen Shot 2020-07-15 at 4 49 49 PM](https://user-images.githubusercontent.com/686933/87610866-642bd680-c6bb-11ea-96b7-e789cd3e397e.png)

**Comment by greenc123** [comment]
Taken care of here: https://github.com/garageScript/databases/pull/142
