### ISSUE TITLE
Implement Mongo DB Module

### ISSUE THREAD

**Issue by songz** [garageScript/databases#18]
Acceptance:
* `startMongoDB` function must start the database
* `closeMongoDB` function must close the database
* `createMongoDB` function must create an account.
* `deleteMongoDB` function must delete an account.
https://www.npmjs.com/package/mongodb

**Comment by greenc123** [comment]
I ended up using mongoose to simplify things
https://www.npmjs.com/package/mongoose

**Comment by greenc123** [comment]
MongoDB cheatsheet:

https://gist.github.com/bradtraversy/f407d642bdc3b31681bc7e56d95485b6
