### ISSUE TITLE
[Bug] - Prevent users from approving their own submissions

### ISSUE THREAD

**Issue by songz** [garageScript/databases#69]
![Screen Shot 2020-06-06 at 4 10 17 PM](https://user-images.githubusercontent.com/686933/83956202-4348a980-a810-11ea-9f31-5ed2ebf0f397.png)

**Comment by hwong0305** [comment]
Additional points to this issue:

- Should prevent users from viewing submissions if they're not a teacher
- Need to fix link to review lessons in curriculum page
